/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package propuestaProyecto;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Empleado extends javax.swing.JPanel {

    public static DefaultTableModel m;
    private Integer idEmpleado;
    final String OP1 = "Ingrese nombre completo del empleado";
    final String OP2 = "Ingrese Usuario";
    final String OP3 = "Ingrese contraseña";

    public Empleado() {
        initComponents();
    }

    public void limpiar() {
        txt_nombreEmpleado.setText(OP1);
        txt_nombreEmpleado.setForeground(new Color(204, 204, 204));
        txt_usuario.setText(OP2);
        txt_usuario.setForeground(new Color(204, 204, 204));
        txt_contrasenia.setText(OP3);
        txt_contrasenia.setForeground(new Color(204, 204, 204));;
    }

    public void animacionIngresar(JTextField a, String op1, JTextField b, String op2, JTextField c, String op3) {
        if (a.getText().equals(op1)) {
            a.setText("");
            a.setForeground(Color.black);
        }
        if (b.getText().isEmpty()) {
            b.setText(op2);
            b.setForeground(new Color(204, 204, 204));
        }
        if (c.getText().isEmpty()) {
            c.setText(op3);
            c.setForeground(new Color(204, 204, 204));
        }
    }

    public void mostrarEmpleados() {
        String est = null;
        try {
            List<POJOs.Empleado> empleado = CRUDs.CRUDEmpleado.universo();
            String titulos[] = {"id Empleado", "Nombre Empleado", "Usuario", "Contraseña", "Estado"};
            m = new DefaultTableModel(null, titulos);
            String columna[] = new String[5];
            for (POJOs.Empleado r : empleado) {
                if (r.getEstado() == true) {
                    est = "Activo";
                    columna[0] = r.getIdEmpleado() + "";
                    columna[1] = r.getNombreEmpleado();
                    columna[2] = r.getUsuario();
                    columna[3] = r.getContrasenia();
                    columna[4] = est;
                }
                m.addRow(columna);
                tablaEmplados.setModel(m);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombreEmpleado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_contrasenia = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        op_guardar = new javax.swing.JButton();
        op_actualizar = new javax.swing.JButton();
        op_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmplados = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jLabel1.setText("Nombre");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        txt_nombreEmpleado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_nombreEmpleado.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombreEmpleado.setText("Ingrese nombre completo del empleado");
        txt_nombreEmpleado.setBorder(null);
        txt_nombreEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nombreEmpleadoMouseClicked(evt);
            }
        });

        txt_usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_usuario.setText("Ingrese Usuario");
        txt_usuario.setBorder(null);
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario");

        txt_contrasenia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_contrasenia.setForeground(new java.awt.Color(204, 204, 204));
        txt_contrasenia.setText("Ingrese contraseña");
        txt_contrasenia.setBorder(null);
        txt_contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_contraseniaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña");

        op_guardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        op_guardar.setForeground(new java.awt.Color(0, 0, 0));
        op_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar 1.png"))); // NOI18N
        op_guardar.setText("GUARDAR");
        op_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        op_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        op_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_guardarActionPerformed(evt);
            }
        });

        op_actualizar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        op_actualizar.setForeground(new java.awt.Color(0, 0, 0));
        op_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar1.png"))); // NOI18N
        op_actualizar.setText("ACTUALIZAR");
        op_actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        op_actualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        op_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_actualizarActionPerformed(evt);
            }
        });

        op_eliminar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        op_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        op_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        op_eliminar.setText("ELIMINAR");
        op_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        op_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        op_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_eliminarActionPerformed(evt);
            }
        });

        tablaEmplados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmplados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpladosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmplados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombreEmpleado)
                            .addComponent(jSeparator1)
                            .addComponent(txt_usuario)
                            .addComponent(jSeparator2)
                            .addComponent(txt_contrasenia)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(op_guardar)
                        .addGap(55, 55, 55)
                        .addComponent(op_actualizar)
                        .addGap(67, 67, 67)
                        .addComponent(op_eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txt_nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(op_eliminar)
                    .addComponent(op_actualizar)
                    .addComponent(op_guardar))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        mostrarEmpleados();
    }//GEN-LAST:event_formPropertyChange

    private void txt_nombreEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreEmpleadoMouseClicked
        animacionIngresar(txt_nombreEmpleado, OP1, txt_usuario, OP2, txt_contrasenia, OP3);
    }//GEN-LAST:event_txt_nombreEmpleadoMouseClicked

    private void txt_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseClicked
        animacionIngresar(txt_usuario, OP2, txt_nombreEmpleado, OP1, txt_contrasenia, OP3);
    }//GEN-LAST:event_txt_usuarioMouseClicked

    private void txt_contraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contraseniaMouseClicked
        animacionIngresar(txt_contrasenia, OP3, txt_usuario, OP2, txt_nombreEmpleado, OP1);
    }//GEN-LAST:event_txt_contraseniaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        limpiar();
    }//GEN-LAST:event_formMouseClicked

    private void op_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_guardarActionPerformed
        boolean bandera = false;
        String est = "Activo";
        String estado, nombreEmpleado, usuario, contrasenia;

        estado = est;
        nombreEmpleado = txt_nombreEmpleado.getText();
        usuario = txt_usuario.getText();
        contrasenia = txt_contrasenia.getText();

        bandera = CRUDs.CRUDEmpleado.insert(estado, nombreEmpleado, usuario, contrasenia);
        if (bandera) {
            JOptionPane.showMessageDialog(null, "Registro incertado con exito");
        } else {
            JOptionPane.showMessageDialog(null, "Registro fallido");
        }
        mostrarEmpleados();
    }//GEN-LAST:event_op_guardarActionPerformed

    private void tablaEmpladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpladosMouseClicked
        try {
            int fsel;
            fsel = tablaEmplados.getSelectedRow();
            if (fsel == -1) {
                JOptionPane.showMessageDialog(null, "NO se puede seleccionar");
            } else {
                int row = tablaEmplados.getSelectedRow();
                String nombreEmpleado, usuario, contrasenia;
                setIdEmpleado(Integer.parseInt(tablaEmplados.getValueAt(row, 0).toString()));
                nombreEmpleado = tablaEmplados.getValueAt(row, 1).toString();
                usuario = tablaEmplados.getValueAt(row, 2).toString();
                contrasenia = tablaEmplados.getValueAt(row, 3).toString();
                txt_nombreEmpleado.setText(nombreEmpleado);
                txt_nombreEmpleado.setForeground(Color.black);
                txt_usuario.setText(usuario);
                txt_usuario.setForeground(Color.black);
                txt_contrasenia.setText(contrasenia);
                txt_contrasenia.setForeground(Color.black);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tablaEmpladosMouseClicked

    private void op_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_actualizarActionPerformed
        boolean bandera=false;
        Integer id;
        String nombreEmpleado,usuario,contrasenia;
        nombreEmpleado=txt_nombreEmpleado.getText();
        usuario=txt_usuario.getText();
        contrasenia=txt_contrasenia.getText();
        id=getIdEmpleado();
        System.out.println(idEmpleado);
        bandera=CRUDs.CRUDEmpleado.update(id, nombreEmpleado, usuario, contrasenia);
        if(bandera){
        JOptionPane.showMessageDialog(null, "Registro modificado con exito");
        mostrarEmpleados();
        limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Modificacion fallida");
        } 
    }//GEN-LAST:event_op_actualizarActionPerformed

    private void op_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_eliminarActionPerformed
        int respuesta;
        boolean bandera=false;
        String est="Inactivo";
        Integer id;
        id=getIdEmpleado();
        respuesta=JOptionPane.showConfirmDialog(null, "¿DESEA ELIMINAR EL CAMPO SELECCIONADO?",
        "ELIMINAR",JOptionPane.YES_NO_OPTION);
        if(respuesta==JOptionPane.YES_OPTION){
        bandera=CRUDs.CRUDEmpleado.anular(id, est);
         if (bandera) {
            JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO");
            mostrarEmpleados();
        }else{
            JOptionPane.showMessageDialog(null, "ERROR AL ELIMINAR");
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_op_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton op_actualizar;
    private javax.swing.JButton op_eliminar;
    private javax.swing.JButton op_guardar;
    private javax.swing.JTable tablaEmplados;
    private javax.swing.JTextField txt_contrasenia;
    private javax.swing.JTextField txt_nombreEmpleado;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the idEmpleado
     */
    public Integer getIdEmpleado() {
        return idEmpleado;
    }

    /**
     * @param idEmpleado the idEmpleado to set
     */
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
}
